### ISSUE TITLE
error loading packages

### ISSUE THREAD

**Issue by tford9** [mgolafshar/kickstartR#3]
I'm getting this error when attempting to load packages:
"""
<img width="727" alt="image" src="https://user-images.githubusercontent.com/6520354/40369106-44a967bc-5dab-11e8-8e58-11abd67e3321.png">
"""
This could be related to the version of R that I'm using: 
"""
<img width="499" alt="image" src="https://user-images.githubusercontent.com/6520354/40369217-7695daa8-5dab-11e8-932f-6f68f7d9030a.png">
"""

I'm not using RStudio.

**Comment by ProfBiscuit** [comment]
Here is the script that works in base R (v3.5.0). If this doesn't work you might need to update your base R to the most recent version.

install.packages("devtools")
# select the cloud-0 cran mirror
library(devtools)
devtools::install_github("mgolafshar/kickstartR")

**Comment by mrbstat** [comment]
Have you tried using Cloud-0 as your CRAN mirror?

**Comment by tford9** [comment]
Ah, so it's worth noting that I am attempting to run an instance of R through SSH to a cluster. While running the code with Rscript it actually doesn't give me the option to select a CRAN mirror. Could it be that I'm trying to use this with command:
```bash
$ Rscript scriptname.R
```

**Comment by mrbstat** [comment]
We just updated the package adding variant 'packages3'. This function has a new 'mirror' argument so that you can specify the CRAN mirror in the function call. You will need to re-install the kickstartR package in order to see this.

Here is a list of the CRAN mirrors https://cran.r-project.org/mirrors.html . Below is an example of the this function call.

pkglist <- "topicmodels scales sp rgdal igraph rgeos"
packages3(pkglist, mirror = 'https://cloud.r-project.org/')

**Comment by tford9** [comment]
This seemed to fix the problem that I was having. Will continue to test. Thanks.

**Comment by mrbstat** [comment]
Saweet. Will rename packages3 as packages and close.
